// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrendsHairShop.Models;

namespace TrendsHairShop.Migrations
{
    [DbContext(typeof(TrendsHairDbContext))]
    [Migration("20201004144723_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TrendsHairShop.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Curly",
                            Description = "Hair with curles"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "straight",
                            Description = "straight hair"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "wavy",
                            Description = "Hair with waves"
                        });
                });

            modelBuilder.Entity("TrendsHairShop.Models.Hair", b =>
                {
                    b.Property<int>("HairId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHairOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HairId");

                    b.HasIndex("CategoryId");

                    b.ToTable("HairPieces");

                    b.HasData(
                        new
                        {
                            HairId = 1,
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://www.styleinterest.com/wp-content/uploads/2016/02/4120416-crochet-braids-hairstyles-.png",
                            ImageUrl = "https://www.styleinterest.com/wp-content/uploads/2016/02/4120416-crochet-braids-hairstyles-.png",
                            InStock = true,
                            IsHairOfTheWeek = true,
                            LongDescription = "The tight spiral curls in this look are perfect for a girl looking for a more polished look.Even better, you don’t have to deal with all the time it takes to curl hair in the morning!",
                            Name = "Afro Kinky tight curles",
                            Price = 12.95m,
                            ShortDescription = "Gives a kinky afro. Crotchet hair"
                        },
                        new
                        {
                            HairId = 2,
                            CategoryId = 2,
                            ImageThumbnailUrl = "https://ae01.alicdn.com/kf/HTB1hnlBbaL7gK0jSZFBq6xZZpXau/Ali-Julia-Hair-Afro-Kinky-Straight-Hair-360-Lace-Front-Wig-Brazilian-Remy-Human-Hair-Wigs.jpg_q50.jpg",
                            ImageUrl = "https://ae01.alicdn.com/kf/HTB1hnlBbaL7gK0jSZFBq6xZZpXau/Ali-Julia-Hair-Afro-Kinky-Straight-Hair-360-Lace-Front-Wig-Brazilian-Remy-Human-Hair-Wigs.jpg_q50.jpg",
                            InStock = true,
                            IsHairOfTheWeek = true,
                            LongDescription = "lovely straight kinky to mimic the look of a blown-out head full of natural hair",
                            Name = "Afro Kinky Straight",
                            Price = 18.95m,
                            ShortDescription = "You'll love it!"
                        },
                        new
                        {
                            HairId = 3,
                            CategoryId = 3,
                            ImageThumbnailUrl = "https://www.dhresource.com/0x0/f2/albu/g8/M00/0F/F5/rBVaV1xMFv6AScriAAKjDa1r1ro271.jpg/unice-kinky-curly-bulks-women-afro-loose.jpg",
                            ImageUrl = "https://www.dhresource.com/0x0/f2/albu/g8/M00/0F/F5/rBVaV1xMFv6AScriAAKjDa1r1ro271.jpg/unice-kinky-curly-bulks-women-afro-loose.jpg",
                            InStock = true,
                            IsHairOfTheWeek = false,
                            LongDescription = "Loose Wave Hair Extensions Wavy Weave Wefts. fdfdfdsffdffdffdfdfdfdfdfdf sdjflkdjfkdfkdjfkd fdfdfdsffdffdffdfdfdfdfdfdf sdjflkdjfkdfkdjfkd fdfdfdsffdf sdjflkdjfkdfkdjfkd fdfdfdsffdf",
                            Name = "Angle waves",
                            Price = 18.95m,
                            ShortDescription = "beautiful wavy hair weave"
                        });
                });

            modelBuilder.Entity("TrendsHairShop.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("HairId")
                        .HasColumnType("int");

                    b.Property<int>("HairQty")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("text");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("HairId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("TrendsHairShop.Models.Hair", b =>
                {
                    b.HasOne("TrendsHairShop.Models.Category", "Category")
                        .WithMany("HairPieces")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrendsHairShop.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("TrendsHairShop.Models.Hair", "Hair")
                        .WithMany()
                        .HasForeignKey("HairId");
                });
#pragma warning restore 612, 618
        }
    }
}
